// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRrQJ0tEKHHoyVzU6MRJ-2QYH39-3YQQ',
    appId: '1:946554830008:web:be6b1aa7520c2b9bdc884d',
    messagingSenderId: '946554830008',
    projectId: 'chatgptproject-d7480',
    authDomain: 'chatgptproject-d7480.firebaseapp.com',
    storageBucket: 'chatgptproject-d7480.appspot.com',
    measurementId: 'G-Y0BK6VW12D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1tTsv5FktVNfujBOwUVIBo31vv7ovcs',
    appId: '1:946554830008:android:28406494841b2d6adc884d',
    messagingSenderId: '946554830008',
    projectId: 'chatgptproject-d7480',
    storageBucket: 'chatgptproject-d7480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCo0wy_tfvpo1i4FHmlR6iTqSG_jdkXqw',
    appId: '1:946554830008:ios:1a3213ca641eb99ddc884d',
    messagingSenderId: '946554830008',
    projectId: 'chatgptproject-d7480',
    storageBucket: 'chatgptproject-d7480.appspot.com',
    iosBundleId: 'com.example.chatGptProject',
  );
}
